baseURL = 'https://github.fightingforme.top/'
languageCode = 'zh-cn'
theme = 'hextra'
title = 'My SRE Knowledge Vault'


# Search
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]




# --- 全局导航栏配置 (Main Menu) ---
[menu]

  # 首页入口
  [[menu.main]]
    identifier = "home"
    name = "首页"
    pageRef = "/"
    weight = 10


  # 列表页
  [[menu.main]]
    identifier = "blog-list"
    name = "博客列表"
    pageRef = "/blog"
    weight = 20



  # 分类（大） 
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 30

  # 标签（小） 
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 40



  # 关于页面
  [[menu.main]]
    identifier = "About"
    name = "关于我"
    pageRef = "/blog/about"
    weight = 50

  # Troubleshooting
  [[menu.main]]
    identifier = "Runbook"
    name = "TroubleShooting"
    pageRef = "/incident-runbook"
    weight = 60








[params]

  [params.hextra]
  # 显式强化配置：确保导航栏开启
  navbar = { enable = true }

  # 显式强化配置：强制开启搜索功能
  [params.hextra.search]
    enable = true



